export interface GlossaryTerm {
  term: string
  definition: string
  category: 'espresso' | 'brew' | 'equipment' | 'milk'
}

const GLOSSARY_RAW: GlossaryTerm[] = [
  { term: 'Bloom', category: 'brew', definition: 'A short pre-wet with a small amount of water (approx. 2× the coffee dose) that lets CO₂ escape before brewing. Improves extraction in pour-over methods.' },
  { term: 'Body', category: 'espresso', definition: 'The mouthfeel of the espresso — how creamy, thick, and full it feels. Determined by oils and colloids in the extract.' },
  { term: 'Brew Ratio', category: 'espresso', definition: 'The ratio of coffee dose to extracted weight (yield). A typical espresso is 1:2 — e.g., 18 g coffee → 36 g yield.' },
  { term: 'Group Head', category: 'equipment', definition: 'The part of the espresso machine where the portafilter is locked in. Delivers water at constant pressure through the coffee puck.' },
  { term: 'Brew Temperature', category: 'espresso', definition: 'Temperature of the water as it passes through the coffee grounds. Typically 88–96°C for espresso. Too hot = over-extraction, too cold = under-extraction.' },
  { term: 'Brew Time', category: 'espresso', definition: 'Time from start to end of the espresso pull. Typically 25–35 seconds. Strongly influenced by grind size and tamp pressure.' },
  { term: 'Burr', category: 'equipment', definition: 'The grinding element in a grinder. Flat burrs (ring-shaped) or conical burrs grind coffee between two surfaces.' },
  { term: 'Channeling', category: 'espresso', definition: 'Water breaks through a channel in the coffee puck instead of flowing evenly. Leads to uneven extraction and sour or bitter results.' },
  { term: 'Crema', category: 'espresso', definition: 'The golden-brown foam layer on top of espresso. Formed by CO₂ bubbles dissolving in fats and emulsifiers. Indicates freshness and correct pressure.' },
  { term: 'Steam Wand', category: 'equipment', definition: 'The metal tube on an espresso machine for frothing milk. Injects steam that incorporates air and heats the milk.' },
  { term: 'Dose', category: 'espresso', definition: 'The measured amount of ground coffee in grams placed in the portafilter basket. Typically 16–20 g for espresso.' },
  { term: 'Pressure', category: 'espresso', definition: 'Water pressure during the espresso pull, measured in bar. Standard is 9 bar. Some machines allow pressure profiling.' },
  { term: 'Dual Boiler', category: 'equipment', definition: 'Machine type with two separate boilers — one for brew water, one for steam. Allows simultaneous brewing and steaming at optimal temperatures.' },
  { term: 'Single Boiler', category: 'equipment', definition: 'Simplest machine type with one boiler for everything. Cannot brew and steam simultaneously — you must wait for the temperature to switch.' },
  { term: 'Espresso', category: 'espresso', definition: 'Concentrated coffee beverage made by forcing hot water at ~9 bar through finely ground coffee. The base of many milk drinks.' },
  { term: 'Extraction', category: 'espresso', definition: 'The process by which flavors, oils, and soluble compounds pass from the coffee grounds into the water. The goal is a balanced extraction (18–22% EY).' },
  { term: 'Extraction Yield (EY)', category: 'espresso', definition: 'The percentage of soluble solids extracted from the coffee grounds. Ideal: 18–22%. Measured with a refractometer.' },
  { term: 'Filter Coffee', category: 'brew', definition: 'Brewing method where water passes through ground coffee and a filter. Produces a clear, lighter coffee without sediment.' },
  { term: 'Flat Burr', category: 'equipment', definition: 'Burr shape with two parallel ring-shaped discs. Grinds evenly and produces a uniform particle size. Typical in high-end grinders.' },
  { term: 'French Press', category: 'brew', definition: 'Brewing method where coarsely ground coffee steeps in hot water and is then separated by pressing a plunger.' },
  { term: 'Inverted (AeroPress)', category: 'brew', definition: 'Upside-down AeroPress method: device sits on the plunger, coffee steeps longer before filtering. Gives more control over steep time.' },
  { term: 'Conical Burr', category: 'equipment', definition: 'Burr shape with a conical inner and ring-shaped outer burr. Produces a bimodal grind — coarse and fine particles. Common in budget grinders.' },
  { term: 'Leveler', category: 'equipment', definition: 'A tool for evenly distributing and leveling the coffee grounds in the basket after dosing. Reduces channeling.' },
  { term: 'Latte Art', category: 'milk', definition: 'The technique of creating patterns (heart, rosetta, tulip) on milk drinks by pouring steamed milk in a controlled way.' },
  { term: 'Grind Setting', category: 'espresso', definition: 'The adjustment on the grinder that determines how fine or coarse the coffee is ground. Finer = slower shot, coarser = faster shot.' },
  { term: 'Microfoam', category: 'milk', definition: 'Fine-textured, velvety milk foam without visible bubbles. Created by correct stretching technique. Ideal for latte art and smooth milk drinks.' },
  { term: 'Moka Pot', category: 'brew', definition: 'A stovetop pot that uses steam pressure to push hot water through coffee grounds. Produces strong, espresso-like coffee without a pump.' },
  { term: 'Over-extraction', category: 'espresso', definition: 'Too many bitter compounds dissolved from the coffee. Result: bitter, astringent, burnt. Cause: too fine, too hot, too long.' },
  { term: 'Puck', category: 'espresso', definition: 'The compressed coffee grounds in the portafilter basket after tamping. A good puck is even, firm, and water-resistant.' },
  { term: 'Pour Over', category: 'brew', definition: 'Hand-brewed filter coffee (V60, Chemex) where water is poured manually in circular motions over the coffee grounds.' },
  { term: 'Preinfusion', category: 'espresso', definition: 'A short pre-wet of the coffee grounds at low pressure (2–4 bar) before the full pull. Evenly saturates the puck and reduces channeling.' },
  { term: 'Refractometer', category: 'equipment', definition: 'An optical device for measuring dissolved solids concentration in coffee (TDS). Enables accurate calculation of extraction yield.' },
  { term: 'RDT (Ross Droplet Technique)', category: 'equipment', definition: 'Method: add a drop of water to the beans before grinding. Reduces static charge and prevents coffee from clinging to the grinder.' },
  { term: 'Roast Level', category: 'espresso', definition: 'Scale of coffee roast from light (fruity, acidic) to dark (chocolatey, bitter). Affects grind setting and optimal brew temperature.' },
  { term: 'Basket', category: 'equipment', definition: 'The metal basket in the portafilter with holes that holds the coffee and distributes water evenly. Various sizes (14–22 g) and precision baskets (VST, IMS).' },
  { term: 'Portafilter', category: 'equipment', definition: 'The handle with metal basket locked into the group head. Holds the coffee grounds during the pull.' },
  { term: 'Stretching', category: 'milk', definition: 'First phase of steaming milk: hold the wand just below the surface, incorporate air until volume increases by ~50%.' },
  { term: 'Stepless Grinder', category: 'equipment', definition: 'A grinder without click-stop steps — grind setting can be adjusted infinitely. More precision than stepped grinders.' },
  { term: 'Tamping', category: 'espresso', definition: 'Pressing the coffee grounds evenly in the basket with a tamper (~15 kg pressure). Creates an even, dense surface for water flow.' },
  { term: 'TDS (Total Dissolved Solids)', category: 'espresso', definition: 'Total dissolved solids in the coffee as a percentage. Espresso: 8–12%, filter coffee: 1–1.5%. Measured with a refractometer.' },
  { term: 'Texturing', category: 'milk', definition: 'Second phase of steaming milk: submerge the wand deeper, swirl milk and heat to 60–65°C. Integrates foam into a silky texture.' },
  { term: 'Thermoblock', category: 'equipment', definition: 'Simple heating system where water is heated through a metal block instead of a boiler. Fast heat-up but less stable temperature.' },
  { term: 'Under-extraction', category: 'espresso', definition: 'Too few flavors dissolved from the coffee. Result: sour, watery, astringent. Cause: too coarse, too cold, too short.' },
  { term: 'V60', category: 'brew', definition: 'Pour-over filter by Hario with a 60° angle and spiral ribs. Water is poured in circular motions. Produces a clean, aromatic coffee.' },
  { term: 'WDT (Weiss Distribution Technique)', category: 'equipment', definition: 'Method: use a thin needle or dedicated tool to stir and distribute coffee grounds in the basket. Breaks up clumps and reduces channeling.' },
  { term: 'Yield', category: 'espresso', definition: 'The weight of the extracted espresso in the cup in grams. Together with the dose it gives the brew ratio (e.g., 18 g dose → 36 g yield = 1:2).' },
  { term: 'Heat Exchanger', category: 'equipment', definition: 'Machine type with one main steam boiler and a separate heat exchanger for brew water. Allows simultaneous brewing and steaming.' },
]

export const GLOSSARY: GlossaryTerm[] = GLOSSARY_RAW.sort((a, b) => a.term.localeCompare(b.term, 'en'))
